# Model Configuration
model:
  id: "microsoft/git-base"
  # For GPU: "cuda", for CPU: "cpu"
  type: "ms-git"
  device: "cuda"
  # Use float16 for faster inference and less memory on GPU
  torch_dtype: "float32"

# Data Paths
paths:
  output_dir: "outputs"

# Generation Parameters
generation:
  # A general prompt to guide the model. Set to null for unconditional generation.
  # prompt: "a detailed accurate description of the scene"
  prompt: null
  num_captions_per_image: 3
  max_new_tokens: 75
  min_length: 20
  do_sample: true
  temperature: 0.2
  top_k: 50
  top_p: 0.95
  repetition_penalty: 1.2

