# Model Configuration
model:
  id: "llava-hf/llava-1.5-7b-hf" # huggingface model ID
  type: "llava"
  # For GPU: "cuda", for CPU: "cpu"
  device: "cuda"
  torch_dtype: "float16"

# Data Paths
paths:
  image_folder: "data/val2017"
  output_dir: "outputs"

# Generation Parameters
generation:
  prompt: |
    You are a precise and objective image analyst. Your task is to describe exactly what you see in the image. 
    List only the visible facts, including people, objects, the setting, and any actions. 
    Do not make assumptions, infer relationships, or guess at what might be happening outside the frame. 
    Provide a direct, factual description. Ensure your description ends in a complete sentence.
  num_captions_per_image: 3
  max_new_tokens: 75
  min_length: 20
  do_sample: true
  temperature: 0.7
  top_k: 50
  top_p: 0.95
  repetition_penalty: 1.2
  
# Evaluation
evaluation:
  reference_captions_path: data/captions_val2017.json